### ISSUE TITLE
Dependabot reports security issue in cryptography v40

### ISSUE THREAD

**Issue by integrajerome** [GlitchCorp/fastapi-another-jwt-auth#18]
Dependabot reports that cryptography package version < 41.0.2 is vulnerable.
Can you please upgrade?
Thank you in advance.

**Comment by sarthak7gupta** [comment]
Created PR #21 for the same. Waiting for the maintainers to approve.

@mmasztalerczuk

**Comment by thuyng-ing** [comment]
@mmasztalerczuk could you please upgrade? Thank you in advance!
