### ISSUE TITLE
Cryptography dependency is outdated

### ISSUE THREAD

**Issue by integrajerome** [GlitchCorp/fastapi-another-jwt-auth#29]
depends on both cryptography (^42.0.2) and fastapi-another-jwt-auth (^0.1.10), version solving failed

![image](https://github.com/GlitchCorp/fastapi-another-jwt-auth/assets/91475647/760fc783-d31b-4b02-b2d3-6167192a093c)

**Comment by CPickens42** [comment]
Hello @mmasztalerczuk, is there any news on that?
I love your project, and I can of pray this one will stay maintained :sweat_smile:

**Comment by jimbobparsons** [comment]
Hi @mmasztalerczuk,

Can you please confirm if this project is maintained?

I require the same update as the original post

**Comment by apptechxonia** [comment]
I jumped to this after fastapi_jwt_auth is not maintained. Required the same update for cryptography

**Comment by mmasztalerczuk** [comment]
Fixed
