### ISSUE TITLE
Dependabot reports security issue in cryptography v36

### ISSUE THREAD

**Issue by integrajerome** [GlitchCorp/fastapi-another-jwt-auth#3]
Dependabot reports that cryptography package version <37.0.0 is vulnerable to two moderate-level security issues.
It recommends upgrading it to version 39.0.1 or later.
However: fastapi-another-jwt-auth (0.1.6) depends on cryptography (>=36.0.2,<37.0.0)

**Comment by mmasztalerczuk** [comment]
Fixed
